[build]
  publish = "public"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    # CORS and security headers (managed here, not in _headers)
    Access-Control-Allow-Origin = "https://www.macrosight.net"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https://www.macrosight.net"

# 🔁 Pretty URL Rewrites
[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/resume"
  to = "/resume.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/projects.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/invest"
  to = "/invest.html"
  status = 200

[[redirects]]
  from = "/experience"
  to = "/experience.html"
  status = 200
