[build]
publish = "/"
command = ""

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "/*.html"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.macrosight.net"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "*"
