[build]
publish = "public"
command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.macrosight.net"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
