name: Deploy & CI Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint source code
        run: npx eslint src/pages/ src/public/ --fix

      - name: Format source code
        run: npx prettier --write src/pages/ src/public/

      - name: Run tests (if defined)
        run: |
          if [ -f package.json ] && grep -q '"test"' package.json; then
            npm run test
          else
            echo "No test script defined. Skipping tests."
          fi

      - name: Check HTML structure (<link>/<script>)
        run: |
          missing=""
          for f in $(find public -type f -name '*.html'); do
            if ! grep -q '<link rel="stylesheet"' "$f" || ! grep -q 'window.addEventListener' "$f"; then
              echo "❌ Missing <link> or <script> in $f"
              missing=1
            fi
          done
          if [ "$missing" = "1" ]; then exit 1; fi

      - name: Check Netlify CORS headers and HTTP status
        run: |
          set -e
          base="https://www.macrosight.net"
          echo "| Page | Status | CORS Header | Notes |" > summary.md
          echo "|------|--------|-------------|-------|" >> summary.md
          fail=0

          for page in $(find public -name '*.html' -exec basename {} \;); do
            url="$base/$page"
            status=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            cors=$(curl -sI "$url" | grep -i 'access-control-allow-origin:')

            if [ "$status" != "200" ]; then
              cors_status="❌"
              notes="Status $status"
              fail=1
            elif ! echo "$cors" | grep -q '*'; then
              cors_status="❌"
              notes="Missing CORS"
              fail=1
            else
              cors_status="✅"
              notes="OK"
            fi

            printf "| %s | %s | %s | %s |\n" "$page" "$status" "$cors_status" "$notes" >> summary.md
          done

          cat summary.md
          if [ "$fail" = "1" ]; then
            echo "❌ Some HTML pages failed validation."
            exit 1
          fi
