name: Netlify HTML Link Check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Netlify HTML endpoints
        run: |
          set -e
          base="https://www.macrosight.net"
          printf "| Page | Status | CORS Header | Notes |\n"
          printf "|------|--------|-------------|-------|\n"
          fail=0
          for page in home about resume projects contact experience invest; do
            url="$base/$page.html"
            status=$(curl -s -o /dev/null -w "%{http_code}" "$url")
            cors=$(curl -s -I "$url" | grep -i 'access-control-allow-origin:')
            notes=""
            if [ "$status" = "200" ] && echo "$cors" | grep -q '*'; then
              cors_status="✅"
            else
              cors_status="❌"
              fail=1
              notes="Check status or CORS"
            fi
            printf "| %s.html | %s | %s | %s |\n" "$page" "$status" "$cors_status" "$notes"
          done
          if [ "$fail" = "1" ]; then exit 1; fi
        shell: bash
